apiVersion: v1
kind: Pod
metadata:
  name: pod-php-fpm
  labels:
    app.kubernetes.io/name: php-fpm-instance
spec:
  volumes:
  - name: wordpress-files
    persistentVolumeClaim:
      claimName: pvc-nginx-php-fpm
  - name: init-php-fpm
    configMap:
      name: conf
      defaultMode: 0744
  containers:
  - name: wphpfpm
    image: ouuss/php-fpm:1
    imagePullPolicy: Always
    envFrom:
    - configMapRef:
        name: conf
    - secretRef:
        name: credentials
    ports:
      - containerPort: 9000
    volumeMounts:
      - name: wordpress-files
        mountPath: /var/www/html
      - name: init-php-fpm
        mountPath: /temp/init.sh
        subPath: init.sh


