apiVersion: v1
kind: ConfigMap
metadata:
  name: conf
data:

  DB_USER: db_user
  DB_HOST: service-mariadb
  DB_NAME: wp_db
  WP_URL: wp_url
  WP_TITLE: wp_title
  ADMIN_WP_USER: admin
  ADMIN_WP_EMAIL: admin@admin.com

  php.conf: |
    server {
      listen 4242;
      root /var/www/html;
      index index.html index.php;

      location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass service-php-fpm:7778;
      }

      location / {
        try_files $uri $uri/ =404;
      }
    }

  init.sh: |
    #!/bin/bash

    set -xe
    echo "********************* hello this is script running *********************"

    # while ! mariadb -u $DB_USER -p$DB_PASS -h $DB_HOST -e "use $DB_NAME"; do
    #   sleep 2
    # done

    # cd /var/www/html
    # mv /temp/wordpress/* .
    # rm -rf /temp/wordpress

    # if [ ! -f "/var/www/html/wp-config.php" ]; then

    #   wp config create --dbname=$DB_NAME --dbuser=$DB_USER --dbpass=$DB_PASS --dbhost=$DB_HOST --allow-root
    #   wp core install --url=$WP_URL --title=$WP_TITLE --admin_user=$ADMIN_WP_USER --admin_password=$ADMIN_WP_PASS --admin_email=$ADMIN_WP_EMAIL --allow-root

    # fi
    exec php-fpm8.2 -F

  init_db.sh: |
    #!/bin/bash

    set -xe

    echo "Begin executing!!!!"

    mariadb -u root -p$MARIADB_ROOT_PASSWORD -e "create database $DB_NAME;
    create user '$DB_USER'@'%' identified by '$DB_PASS';
    grant all privileges on $DB_NAME.* to '$DB_USER'@'%' identified by '$DB_PASS';
    flush privileges;"

    echo "Done!!!!"