apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app.kubernetes.io/name: nginxInstance
spec:
  containers:
    - image: nginx:latest
      name: nginxssl
      ports:
        - containerPort: 4242
      volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d/nginxPhpFpm.conf
          subPath: php.conf
        - name: wordpress-files
          mountPath: /var/www/html
  volumes:
    - name: nginx-conf
      configMap:
        name: conf
    - name: wordpress-files
      persistentVolumeClaim:
        claimName: nginx-php-fpm-pvc

