apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app.kubernetes.io/name: nginxInstance
spec:
  containers:
    - image: nginx:latest
      name: nginxssl
      ports:
        - containerPort: 4242
      volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d/nginxPhpFpm.conf
          subPath: php.conf
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 128Mi
  volumes:
    - name: nginx-conf
      configMap:
        name: nginx-php-fpm-cm

