apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx
  labels:
    app.kubernetes.io/name: nginxInstance
spec:
  volumes:
    - name: nginx-conf
      configMap:
        name: conf
    - name: wordpress-files
      persistentVolumeClaim:
        claimName: pvc-nginx-php-fpm
  containers:
    - image: nginx:latest
      name: nginxssl
      ports:
        - containerPort: 4242
      volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d/nginxPhpFpm.conf
          subPath: php.conf
        - name: wordpress-files
          mountPath: /var/www/html


      # resources:
      #   limits:
      #     memory: 120Mi
      #     cpu: 100m

