apiVersion: v1
kind: Pod
metadata:
  name: php-fpm-pod
  labels:
    app.kubernetes.io/name: php-fpm-instance
spec:
  volumes:
    - name: wordpress-files
      persistentVolumeClaim:
        claimName: nginx-php-fpm-pvc
    - name: init-php-fpm
      configMap:
        name: conf
        defaultMode: 0744
  containers:
    - name: wphpfpm
      image: joseeeen/php-fpm:wp.2
      ports:
        - containerPort: 9000
      volumeMounts:
        - name: wordpress-files
          mountPath: /var/www/html
        - name: init-php-fpm
          mountPath: /temp/init.sh
          subPath: init.sh

