apiVersion: v1
kind: Service
metadata:
  name: service-nginx
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: nginxInstance
  ports:
  - port: 7777
    targetPort: 4242
    nodePort: 30001
